//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public System.Guid ID { get; set; }
        public string TenSanPham { get; set; }
        public string HinhAnh { get; set; }
        public string ThongTin { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<System.DateTime> NgayNhapHang { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public string TenDanhMuc { get; set; }
    }
}
